@url_base = http://127.0.0.1:8000

### Get begging
GET {{url_base}}

### post create a new user 0
POST {{url_base}}/auth/signup
Content-Type: application/json

{
  "user_id": "a239451c-8525-4376-b8ca-070dd799a1a5",
  "email": "luisanahenmary@gmail.com",
  "user_name": "CiberWitch123$",
  "password": "Caraota123()",
  "first_name": "Luisana",
  "last_name": "Perez",
  "birth_date": "1997-12-16"
}

### post create a new user 1
POST {{url_base}}/auth/signup
Content-Type: application/json

{
  "user_id": "a239501c-8525-4376-b8ca-070dd449a1a5",
  "email": "jesusandres@gmail.com",
  "user_name":"FireGrunge13",
  "password": "itadori123/",
  "first_name": "jesus",
  "last_name": "Perez",
  "birth_date": "2004-07-19"
}

### get show all users
GET {{url_base}}/users

### get show a users 0
GET {{url_base}}/users/a239451c-8525-4376-b8ca-070dd799a1a5

### get show a users 1
GET {{url_base}}/users/a239451c-8525-4376-b8ca-070dd449a1a5

### get show a users 2
GET {{url_base}}/users/a239501c-8525-4376-b8ca-070dd449a1a5

### update a users 0
PUT  {{url_base}}/users/update/a239451c-8525-4376-b8ca-070dd799a1a5

{
  "user_id": "a239501c-8525-4376-b8ca-070dd449a1a5",
  "email": "luisanahenmary@gmail.com",
  "user_name":"CiberWitch123$",
  "password": "Force125&",
  "first_name": "Luisana",
  "last_name": "Perez",
  "birth_date": "1997-12-16"
}

### update a users 0
DELETE   {{url_base}}/users/delete/a239501c-8525-4376-b8ca-070dd449a1a5

### post the 1º tweet of user 0
POST {{url_base}}/tweet
Content-Type: application/json

{
  "tweet_id": "d1c9d4bb-5e46-4a4c-99c1-6b1840affe95",
  "content": "my first tweet",
  "created_at": "2019-08-24T14:15:22Z",
  "updated_at": "2019-08-24T14:15:22Z",
  "by": {
    "user_id": "a239451c-8525-4376-b8ca-070dd799a1a5",
    "email": "luisanahenmary@gmail.com",
    "user_name": "CiberWitch123$",
    "first_name": "Luisana",
    "last_name": "Perez",
    "birth_date": "1997-12-16"
  }
}

### post the 2º tweet of user 0
POST {{url_base}}/tweet
Content-Type: application/json

{
  "tweet_id": "d1c9d4bb-5e46-4a4c-99c1-6b1840affe85",
  "content": "my second tweet",
  "created_at": "2019-08-24T14:15:22Z",
  "updated_at": "2019-08-24T14:15:22Z",
  "by": {
    "user_id": "a239451c-8525-4376-b8ca-070dd799a1a5",
    "email": "luisanahenmary@gmail.com",
    "user_name": "CiberWitch123$",
    "first_name": "Luisana",
    "last_name": "Perez",
    "birth_date": "1997-12-16"
  }
}

### post the 2º tweet of user 1
POST {{url_base}}/tweet
Content-Type: application/json

{
  "tweet_id": "d2c9d4bb-5e46-4a4c-99c1-6b1840affe95",
  "content": "my first tweet, grunge",
  "created_at": "2019-08-24T14:15:22Z",
  "updated_at": "2019-08-24T14:15:22Z",
  "by": {
    "user_id": "a239501c-8525-4376-b8ca-070dd449a1a5",
    "email": "jesusandres@gmail.com",
    "user_name": "FireGrunge13",
    "first_name": "Jesus",
    "last_name": "Perez",
    "birth_date": "1997-12-16"
  }
}

### get create a new user 1
GET {{url_base}}/tweets