@url_base = http://127.0.0.1:8000

### Get begging
GET {{url_base}}

### post create a new user
POST {{url_base}}/auth/signup
Content-Type: application/json

{
  "user_id": "a239451c-8525-4376-b8ca-070dd799a1a5",
  "email": "luisanahenmary@gmail.com",
  "user_name":"CiberWitch",
  "password": "caraota123()",
  "first_name": "Luisana",
  "last_name": "Perez",
  "birth_date": "2004-07-19"
}

### get show all users
GET {{url_base}}/users
