@url_base = http://127.0.0.1:8000

### Create a new user U1
POST {{url_base}}/auth/signup
Content-Type: application/json

{
  "user_id": "a239451c-8525-4376-b8ca-070dd799a1a5",
  "email": "luisanahenmary@gmail.com",
  "user_name": "LPC1612",
  "password": "Caraota123()",
  "first_name": "Luisana",
  "last_name": "Perez",
  "birth_date": "1997-12-16"
}

### Create a new user U2
POST {{url_base}}/auth/signup
Content-Type: application/json

{
  "user_id": "a239501c-8525-4376-b8ca-070dd449a1a5",
  "email": "jesusandres@gmail.com",
  "user_name":"Jisus07",
  "password": "Copito67/",
  "first_name": "Jesus",
  "last_name": "Perez",
  "birth_date": "2004-07-19"
}

### Create a new user U3
POST {{url_base}}/auth/signup
Content-Type: application/json

{
  "user_id": "a239501c-8525-4376-b8ca-070dd469a1a5",
  "email": "marisabelp@gmail.com",
  "user_name":"Marucha667",
  "password": "Millim66%",
  "first_name": "Marisabel",
  "last_name": "Cardenas",
  "birth_date": "1994-03-17"
}


